# Generated by Django 4.1.5 on 2023-02-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_followerscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile_img',
            field=models.ImageField(default='blank-profile-picture-973460_1280.png', upload_to=''),
        ),
    ]
